export const psychologistRoutes = {
  profile: '/psychologist/profile',
  verifyProfile: '/auth/psychologist/verify-profile',
  slot: '/psychologist/slot',
  slotById: (slotId: string) => `/psychologist/slot/${slotId}`,
  kyc: '/psychologist/kyc',
  consultations: '/psychologist/consultations',
  consultationCancel: (consultationId: string) => `/psychologist/consultation/${consultationId}/cancel`,
  consultationHistory: '/psychologist/consultation/history',
  patientHistory: (patientId: string) => `/psychologist/patients/${patientId}/history`,
  pendingPayout: '/psychologist/payout/pending',
  requestPayout: '/psychologist/payout-requests',
  payoutHistory: '/psychologist/payout-requests',
  updateNotes: (consultationId: string) => `/psychologist/consultation/${consultationId}/notes`,
  getReviews: (psychologistId: string) => `/psychologist/${psychologistId}/reviews`,
  revenueStats: '/psychologist/revenue-stats',
  getBookingTrend: '/psychologist/booking-trend',
  getClientTrend: '/psychologist/client-trend',
  getTopUsers: '/psychologist/top-users',
  getTopConsultations: '/psychologist/top-consultations',
  getTotals: '/psychologist/totals',
} as const;
