export enum NotificationType {
    CONSULTATION_BOOKED = 'CONSULTATION_BOOKED',
    CONSULTATION_CANCELLED = 'CONSULTATION_CANCELLED',
    CONSULTATION_REMINDER = 'CONSULTATION_REMINDER',
    NEW_MESSAGE = 'NEW_MESSAGE',
    PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
    PAYMENT_FAILED = 'PAYMENT_FAILED',
    FEEDBACK_RECEIVED = 'FEEDBACK_RECEIVED',
}