export const psychologistFrontendRoutes = {
  verification: '/psychologist/verification',
  profile: '/psychologist/profile',
  editProfile: '/psychologist/edit-profile',
  changePassword: '/psychologist/change-password',
  kyc: '/psychologist/kyc',
  slot: '/psychologist/slot',
  consultations: '/psychologist/consultations',
  consultationDetailPath: '/psychologist/consultations/:consultationId',
  consultationDetail: (consultationId: string) => `/psychologist/consultations/${consultationId}`,
  chat: '/psychologist/chat',
  chatWithConsultationPath: '/psychologist/chat/:consultationId',
  chatWithConsultation: (consultationId: string) => `/psychologist/chat/${consultationId}`,
  videoCallPath: '/psychologist/consultations/:consultationId/video',
  videoCall: (consultationId: string) => `/psychologist/consultations/${consultationId}/video`,
  consultationHistory: '/psychologist/consultation/history',
  consultationHistoryDetailPath: '/psychologist/consultation/:consultationId/history',
  consultationHistoryDetail: (consultationId: string) =>
    `/psychologist/consultation/${consultationId}/history`,
  patientHistoryPath: '/psychologist/patients/:patientId/history',
  patientHistory: (patientId: string) => `/psychologist/patients/${patientId}/history`,
  myEarning: '/psychologist/my-earning',
  reviews: '/psychologist/reviews',
  dashboard: '/psychologist/dashboard',

} as const;
