export const userFrontendRoutes = {
  psychologist: '/user/psychologists',
  psychologistDetailPath: '/user/psychologists/:id',
  psychologistDetail: (id: string) => `/user/psychologists/${id}`,
  services: '/user/services',
  success: '/user/success',
  cancel: '/user/cancel',
  profile: '/user/profile',
  changePassword: '/user/change-password',
  consultations: '/user/consultations',
  consultationDetailPath: '/user/consultations/:id',
  consultationDetail: (id: string) => `/user/consultations/${id}`,
  chat: '/user/chat',
  chatByConsultationPath: '/user/chat/:consultationId',
  chatByConsultation: (consultationId: string) => `/user/chat/${consultationId}`,
  wallet: '/user/wallet',
  videoCallPath: '/user/consultations/:id/video',
  videoCall: (id: string) => `/user/consultations/${id}/video`,
  consultationDetailPageAfterVideoCall: (role: string, id: string) => `${role}/consultations/${id}`,
  consultationHistory: '/user/consultation/history',
  consultationHistoryDetailPath: '/user/consultation/:consultationId/history',
  consultationHistoryDetail: (consultationId: string) => `/user/consultation/${consultationId}/history`,
} as const;
