export const userFrontendRoutes = {
  psychologist: '/user/psychologists',
  psychologistDetailPath: '/user/psychologists/:psychologistUserId',
  psychologistDetail: (psychologistUserId: string) => `/user/psychologists/${psychologistUserId}`,
  services: '/user/services',
  success: '/user/success',
  cancel: '/user/cancel',
  profile: '/user/profile',
  changePassword: '/user/change-password',
  consultations: '/user/consultations',
  consultationDetailPath: '/user/consultations/:consultationId',
  consultationDetail: (consultationId: string) => `/user/consultations/${consultationId}`,
  chat: '/user/chat',
  chatByConsultationPath: '/user/chat/:consultationId',
  chatByConsultation: (consultationId: string) => `/user/chat/${consultationId}`,
  wallet: '/user/wallet',
  videoCallPath: '/user/consultations/:consultationId/video',
  videoCall: (consultationId: string) => `/user/consultations/${consultationId}/video`,
  consultationDetailPageAfterVideoCall: (role: string, consultationId: string) => `/${role}/consultations/${consultationId}`,
  consultationHistory: '/user/consultation/history',
  consultationHistoryDetailPath: '/user/consultation/:consultationId/history',
  consultationHistoryDetail: (consultationId: string) => `/user/consultation/${consultationId}/history`,
} as const;
